table DIM_TIEMPO
	lineageTag: 54aaf638-01fc-41d3-8b0e-bf69a54eb8d8

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a0cc40b-4fb4-4ed5-96a8-f4a48f387b54
		summarizeBy: none
		sourceColumn: fecha

		variation Variation
			isDefault
			relationship: a3294b25-041f-47a3-ba56-34bde16dbf46
			defaultHierarchy: LocalDateTable_022e5ecc-72b8-4c7b-9163-880c761455a7.'Jerarquía de fechas'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column año
		dataType: int64
		formatString: 0
		lineageTag: 5ad17330-9a9f-4dbf-8a76-9d9378549f53
		summarizeBy: sum
		sourceColumn: año

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		formatString: 0
		lineageTag: 279bd62a-72cd-43a7-af94-b9b58cf1c73f
		summarizeBy: sum
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column mes_nombre
		dataType: string
		lineageTag: d6552a71-71d5-4561-bd23-3c6cc38bc5d0
		summarizeBy: none
		sourceColumn: mes_nombre

		annotation SummarizationSetBy = Automatic

	column trimestre
		dataType: int64
		formatString: 0
		lineageTag: a9bec3a6-a420-40d5-84c8-c5a0b2e0b4df
		summarizeBy: sum
		sourceColumn: trimestre

		annotation SummarizationSetBy = Automatic

	column semana
		dataType: int64
		formatString: 0
		lineageTag: 2cc70019-f1ac-40b8-91f8-f81e87ba12e4
		summarizeBy: sum
		sourceColumn: semana

		annotation SummarizationSetBy = Automatic

	column dia_semana
		dataType: int64
		formatString: 0
		lineageTag: a40a3d26-7184-4add-bb38-8d87f262599e
		summarizeBy: sum
		sourceColumn: dia_semana

		annotation SummarizationSetBy = Automatic

	column dia_semana_nombre
		dataType: string
		lineageTag: ec838b97-7876-42b1-b8c5-d33926963382
		summarizeBy: none
		sourceColumn: dia_semana_nombre

		annotation SummarizationSetBy = Automatic

	partition DIM_TIEMPO = m
		mode: import
		source = ```
				// Esta NO se crea desde la tabla principal, sino generada
				let
				    // Obtener rango de fechas de la tabla principal
				    FechaMin = List.Min(BASE[fecha]),
				    FechaMax = List.Max(BASE[fecha]),
				    
				    // Generar calendario
				    Fechas = List.Dates(FechaMin, Duration.Days(FechaMax - FechaMin) + 1, #duration(1,0,0,0)),
				    
				    // Convertir a tabla
				    TablaFechas = Table.FromList(Fechas, Splitter.SplitByNothing(), {"fecha"}, null, ExtraValues.Error),
				    
				    // Agregar columnas de tiempo
				    AgregarAño = Table.AddColumn(TablaFechas, "año", each Date.Year([fecha]), Int64.Type),
				    AgregarMes = Table.AddColumn(AgregarAño, "mes", each Date.Month([fecha]), Int64.Type),
				    AgregarMesNombre = Table.AddColumn(AgregarMes, "mes_nombre", each Date.MonthName([fecha]), type text),
				    AgregarTrimestre = Table.AddColumn(AgregarMesNombre, "trimestre", each Date.QuarterOfYear([fecha]), Int64.Type),
				    AgregarSemana = Table.AddColumn(AgregarTrimestre, "semana", each Date.WeekOfYear([fecha]), Int64.Type),
				    AgregarDiaSemana = Table.AddColumn(AgregarSemana, "dia_semana", each Date.DayOfWeek([fecha]), Int64.Type),
				    AgregarDiaSemanaNombre = Table.AddColumn(AgregarDiaSemana, "dia_semana_nombre", each Date.DayOfWeekName([fecha]), type text)
				in
				    AgregarDiaSemanaNombre
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

